# This workflow will build a MuleSoft project and deploy to CloudHub

name: Build and Deploy Mule Applications
run-name: Deploy ${{ github.event.inputs.application }} to ${{ github.event.inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
     inputs:
       environment:
         type: environment
         description: Select the environment
         default: dev
         required: true
       application:
         type: choice
         description: Select the mule application
         options:
         - helloworld-api
         - student-api
         - customer-api
         - sayhello1
         required: true
    
jobs:
  build:
    
    name: Build & Deploy mule application
    defaults:
      run:
        working-directory: ${{ github.event.inputs.application }}
        
    # runs-on: regular-maven
    runs-on: ubuntu-latest
    env:
      CLIENT_ID: ${{secrets.CLIENT_ID}}
      CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      ENVIRONMENT: ${{github.event.inputs.environment}}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin' # Options include: temurin, zulu, adopt, oracle, corretto
        cache: 'maven'          # Cleans up and speeds up builds ('maven' or 'gradle')

    - name: Add repo credentials
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: |
          [{
           "id": "my-exchange-release",
           "username": "~~~Client~~~",
           "password": "${{ secrets.CLIENT_ID}}~?~${{secrets.CLIENT_SECRET }}"
          },
          {
           "id": "anypoint-exchange-v3",
           "username": "~~~Client~~~",
           "password": "${{ secrets.CLIENT_ID}}~?~${{secrets.CLIENT_SECRET }}"
          }]

    - name: Build with maven
      if: ${{ github.event.inputs.environment == 'dev' }}
      run: mvn -B clean package --no-transfer-progress --file pom.xml
  
    - name: Upload to Exchange
      if: ${{ github.event.inputs.environment == 'dev' }}
      run: mvn deploy --no-transfer-progress --file pom.xml
    
    - name: Set Environment Specific Variables
      id: sets-deployment-config-values
      run: |
        case $ENVIRONMENT in
        "dev")  echo "updateStrategy=recreate" >> $GITHUB_ENV
                echo "clustered=false" >> $GITHUB_ENV
                echo "enforceDeployingReplicasAcrossNodes=false" >> $GITHUB_ENV;;
        "test") echo "updateStrategy=recreate" >> $GITHUB_ENV
                echo "clustered=false" >> $GITHUB_ENV
                echo "enforceDeployingReplicasAcrossNodes=false" >> $GITHUB_ENV;;
        "prod") echo "updateStrategy=recreate" >> $GITHUB_ENV
                echo "clustered=true" >> $GITHUB_ENV
                echo "enforceDeployingReplicasAcrossNodes=false" >> $GITHUB_ENV;;
        esac
    - name: Deploy to Target
      run: mvn deploy -DmuleDeploy -DskipTests --no-transfer-progress --file pom.xml
